### ISSUE TITLE
plots are not generated by memory-usage-analyzer

### ISSUE THREAD

**Issue by bravindr** [intel/memory-usage-analyzer#3]
How to reproduce:
Start with a new workspace and following instructions on running example workload(baseline)
https://github.com/intel-innersource/applications.benchmarking.memory-usage-analyzer/blob/master/tests/example/README.md#simple-workload---baseline

Expected Results:
No errors and the plot will be generated in the profile directory

Actual results:
**** Closing profile/baseline/stats.csv.gz
profile/baseline
Traceback (most recent call last):
  File "/home/bravindr/virtualenv/bin/plot.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/bravindr/memory-usage-analyzer/src/analyzer/plot.py", line 10, in <module>
    from bokeh.io import save
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/io/__init__.py", line 24, in <module>
    from .doc import curdoc
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/io/doc.py", line 29, in <module>
    from .state import curstate
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/io/state.py", line 53, in <module>
    from ..document import Document
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/document/__init__.py", line 50, in <module>
    from .document import DEFAULT_TITLE ; DEFAULT_TITLE
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/document/document.py", line 57, in <module>
    from ..core.query import find, is_single_string_selector
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/core/query.py", line 35, in <module>
    from ..model import Model
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/model/__init__.py", line 25, in <module>
    from .data_model import DataModel
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/model/data_model.py", line 25, in <module>
    from .model import Model
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/model/model.py", line 38, in <module>
    from ..core import properties as p
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/core/properties.py", line 273, in <module>
    from .property.auto import Auto; Auto
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/core/property/auto.py", line 24, in <module>
    from .enum import Enum
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/core/property/enum.py", line 27, in <module>
    from .primitive import String
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/bokeh/core/property/primitive.py", line 37, in <module>
    bokeh_bool_types += (np.bool8,)
  File "/home/bravindr/virtualenv/lib64/python3.9/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'
Loading stats from profile/baseline/stats.csv.gz
Loading stats from profile/baseline/stats.csv.gz

**Comment by bravindr** [comment]
It seems like the issue is related to the incompatibility between the bokeh and numpy versions.
We have been reverting to an older version of bokeh,  bokeh==2.4.3, to get the plots scaled properly. The new version of the plots shrinks the plots and this was a work around.

Here are a few suggestons:
1. Updated bokeh and numpy to the latest version (remove 2.4.3 revert) and fix the scaling issues in the plots. An example of the scaling issue is here - https://dcsorepo.jf.intel.com:8080/iax/memoryusageanalyzer-plots.html
2. If we cannot get the scaling issue resolved, we may need to revert numpy to a version that is compatible with bokeh.

**Comment by pallavigopal** [comment]
Fixed in the latest release v.1.0.1
